CREATE SCHEMA IF NOT EXISTS TIENDA;

USE TIENDA;

CREATE TABLE IF NOT EXISTS TIENDAS(
  CODIGO VARCHAR(45) NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  direccion VARCHAR(45) NOT NULL,
  telefono VARCHAR(8) NOT NULL,
	telefono2 VARCHAR(8),
	email VARCHAR(45),
	horario VARCHAR(45),
  PRIMARY KEY(CODIGO)
);

CREATE TABLE IF NOT EXISTS PRODUCTO(
	CODIGO VARCHAR(45) NOT NULL,
	nombre VARCHAR(45) NOT NULL,
	fabricante VARCHAR(45) NOT NULL,
  descripcion VARCHAR(200),
  garantia VARCHAR(45),
	PRIMARY KEY(CODIGO)
);

CREATE TABLE IF NOT EXISTS EXISTENTES(
  ID INT NOT NULL AUTO_INCREMENT,
  cantidad INT NOT NULL,
  precio DOUBLE NOT NULL,
  CODIGO_TIENDA_EXISTENCIA VARCHAR(45) NOT NULL,
  codigo_producto VARCHAR(45) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(CODIGO_TIENDA_EXISTENCIA) REFERENCES TIENDAS(CODIGO),
  FOREIGN KEY(codigo_producto) REFERENCES PRODUCTO(CODIGO)
);

CREATE TABLE IF NOT EXISTS CLIENTE(
	NIT VARCHAR(13) NOT NULL,
	nombre VARCHAR(45) NOT NULL,
	telefono VARCHAR(8) NOT NULL,
  dpi VARCHAR(13),
  credito DOUBLE,
  email VARCHAR(45),
  direccion VARCHAR(45),
	PRIMARY KEY(NIT)
);

CREATE TABLE IF NOT EXISTS PEDIDO(
  ID INT NOT NULL AUTO_INCREMENT,
  CODIGO VARCHAR(45) NOT NULL,
	fecha DATE NOT NULL,
  total DOUBLE,
  anticipo DOUBLE,
  cantidad_articulos INT NOT NULL,
  tienda_origen VARCHAR(45) NOT NULL,
  tienda_destino VARCHAR(45) NOT NULL,
  NIT_cliente VARCHAR(13) NOT NULL,
  codigo_producto VARCHAR(45),
	PRIMARY KEY(ID),
	FOREIGN KEY(tienda_origen) REFERENCES TIENDAS(CODIGO),
	FOREIGN KEY(tienda_destino) REFERENCES TIENDAS(CODIGO),
  FOREIGN KEY(NIT_cliente) REFERENCES CLIENTE(NIT)
);

CREATE TABLE IF NOT EXISTS EMPLEADO(
  CODIGO VARCHAR(45) NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  telefono VARCHAR(8) NOT NULL,
  DPI VARCHAR(13) NOT NULL,
  NIT VARCHAR(13),
  EMAIL VARCHAR(45) NOT NULL,
  direccion VARCHAR(45) NOT NULL,
  PRIMARY KEY(CODIGO)
);

CREATE TABLE IF NOT EXISTS ENVIOS(
  ID INT NOT NULL AUTO_INCREMENT,
  codigo_tienda_origen VARCHAR(45) NOT NULL,
  codigo_tienda_destino VARCHAR(45) NOT NULL,
  tiempo_traslado INT NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(codigo_tienda_origen) REFERENCES TIENDAS(CODIGO),
  FOREIGN KEY(codigo_tienda_destino) REFERENCES TIENDAS(CODIGO)
);
