/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frontend.venta;

import com.backend.conectionDB.ConeccionDB;
import com.backend.conectionDB.modelo.ClienteDB;
import com.backend.entidad.*;
import com.frontend.VentanaTienda;
import com.tienda.utiles.Utiles;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luis
 */
public class VentaForm extends javax.swing.JFrame {

    private VentanaTienda ventanaTienda;
    private Tienda tienda;
    private Sistema sistema;
    private List<Producto> productosCombo;
    private List<Cliente> clientes;
    private DetalleCompra detalleCompra;
    private List<Producto> productosDetalle;

    private DefaultTableModel dfm;

    private Cliente cliente;

    /**
     *
     * @param ventanaTienda
     * @param tienda
     * @param sistema
     * @throws java.sql.SQLException
     */
    public VentaForm(VentanaTienda ventanaTienda, Tienda tienda, Sistema sistema) throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        int tam = 25;
        Utiles.ponerIconoButton(btnNuevaVenta, "iconos/addColorBlack.png", tam);
        Utiles.ponerIconoButton(btnRegresarTienda, "iconos/salir.jpeg", tam);
        Utiles.ponerIconoButton(btnOutoff, "iconos/outRed.jpeg");
        this.sistema = sistema;
        this.tienda = tienda;
        this.ventanaTienda = ventanaTienda;

        this.productosCombo = sistema.getProductoExistenciaDB().getAllProductosByTienda(tienda.getCodigo());
        this.clientes = sistema.getClienteDB().getClientesAllClientes(ConeccionDB.getConnection(), ClienteDB.SELECT_ALL_CLIENTES);

        llenarCombo(productosCombo);
        llenarComboClientes(clientes);

        this.detalleCompra = new DetalleCompra();
        this.productosDetalle = new ArrayList<>();
        this.detalleCompra.setProductos((ArrayList<Producto>) productosDetalle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboProduts = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCarrito = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        comboClientes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtBusquedaNit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnFinalizarCompra = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnNuevaVenta = new javax.swing.JButton();
        btnRegresarTienda = new javax.swing.JButton();
        btnOutoff = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setText("Seleccione producto:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comboProduts.setMaximumSize(new java.awt.Dimension(300, 300));

        jLabel1.setText("Cantidad:");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtCantidad.setMaximumSize(new java.awt.Dimension(300, 300));
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        btnAgregar.setText("Agregar al carrito");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboProduts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProduts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnAgregar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tableCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio", "Cantidad", "Subtotal", "Quitar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCarritoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCarrito);

        jLabel3.setText("Seleccione NIT del cliente:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtBusquedaNit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaNitKeyReleased(evt);
            }
        });

        jLabel4.setText("Buscar al clinte por nit:");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnFinalizarCompra.setText("Finalizar compra");
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBusquedaNit, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                            .addComponent(comboClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(12, 12, 12))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnFinalizarCompra)
                .addGap(32, 32, 32))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        btnNuevaVenta.setBackground(new java.awt.Color(0, 51, 255));
        btnNuevaVenta.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnNuevaVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaVenta.setText("Nueva venta");
        btnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaVentaActionPerformed(evt);
            }
        });

        btnRegresarTienda.setBackground(new java.awt.Color(255, 0, 51));
        btnRegresarTienda.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnRegresarTienda.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarTienda.setText("Regresar a la tienda");
        btnRegresarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarTiendaActionPerformed(evt);
            }
        });

        btnOutoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutoffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnNuevaVenta)
                .addGap(18, 18, 18)
                .addComponent(btnRegresarTienda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOutoff, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnNuevaVenta)
                .addComponent(btnRegresarTienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOutoff, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );

        jTabbedPane1.addTab("", jPanel1);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap(1233, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(481, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        setVisible(false);
        this.ventanaTienda.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void txtBusquedaNitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaNitKeyReleased
        try {
            this.clientes = this.sistema.getClienteDB().getClientesWhitFilter(ConeccionDB.getConnection(), txtBusquedaNit.getText(), ClienteDB.FILTRO_NIT);
            llenarComboClientes(clientes);
        } catch (SQLException ex) {
            Logger.getLogger(VentaForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtBusquedaNitKeyReleased

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        int indice = this.comboProduts.getSelectedIndex();
        Producto auxi = (Producto) productosCombo.get(indice).clone();
        if (txtCantidad.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Debes agregar una cantidad de productos.");
        } else {
            if (productoEnCarrito(productosCombo.get(indice), detalleCompra.getProductos()) == null) {
                if (productosCombo.get(indice).getCantidad() >= (Integer.parseInt(txtCantidad.getText()))) {
                    auxi.setCantidad(Integer.parseInt(txtCantidad.getText()));
                    detalleCompra.getProductos().add(auxi);
                } else {
                    iniciarProcesoPedido();
                }
            } else {
                Producto agregado = productoEnCarrito(auxi, detalleCompra.getProductos());
                if (productosCombo.get(indice).getCantidad() >= (agregado.getCantidad() + Integer.parseInt(txtCantidad.getText()))) {
                    agregado.setCantidad(agregado.getCantidad() + Integer.parseInt(txtCantidad.getText()));
                } else {
                    iniciarProcesoPedido();
                }
            }
        }
        System.out.println(Arrays.deepToString(detalleCompra.getProductos().toArray()));
        llenarTable(detalleCompra.getProductos());
        this.txtCantidad.setText("");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tableCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCarritoMouseClicked
        // TODO add your handling code here:
        int fila = this.tableCarrito.getSelectedRow();
        int columna = this.tableCarrito.getSelectedColumn();
        if (columna == 4) {
            this.detalleCompra.getProductos().remove(fila);
            llenarTable(detalleCompra.getProductos());
        }
    }//GEN-LAST:event_tableCarritoMouseClicked

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        // TODO add your handling code here:
        if (detalleCompra.getProductos().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No ha agregado productos a la venta.");
        } else {

            this.cliente = this.clientes.get(this.comboClientes.getSelectedIndex());
            int opcion = JOptionPane.showConfirmDialog(this, "¿Esta seguro que ha seleccionado el cliente correcto? " + this.cliente.getInfoVenta());
            switch (opcion) {
                case 0:
                    System.out.println("confirmado si es");
                    break;
                case 1:
                    System.out.println("confirmado no es");
                    break;
            }

        }

    }//GEN-LAST:event_btnFinalizarCompraActionPerformed

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        // TODO add your handling code here:
        this.detalleCompra = new DetalleCompra();
        this.productosDetalle = new ArrayList<>();
        this.detalleCompra.setProductos((ArrayList<Producto>) productosDetalle);
        this.productosCombo = sistema.getProductoExistenciaDB().getAllProductosByTienda(tienda.getCodigo());
        llenarCombo(this.productosCombo);
        this.txtCantidad.setText("");
        this.dfm.setRowCount(0);
    }//GEN-LAST:event_btnNuevaVentaActionPerformed

    private void btnOutoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutoffActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnOutoffActionPerformed

    private void btnRegresarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarTiendaActionPerformed

        setVisible(false);
        this.ventanaTienda.setVisible(true);
    }//GEN-LAST:event_btnRegresarTiendaActionPerformed

    private void iniciarProcesoPedido() {
        int op = JOptionPane.showConfirmDialog(this, "No hay suficientes unidades de este producto.\n"
                + "¿Deseas hacer un pedido?");
        System.out.println(op);
    }

    private void llenarCombo(List<Producto> productos) {
        this.comboProduts.removeAllItems();
        for (Producto productoCombo : productos) {
            this.comboProduts.addItem(productoCombo.getInfoVenta());
        }
    }

    private void llenarComboClientes(List<Cliente> clientes) {
        this.comboClientes.removeAllItems();
        for (Cliente clienteCombo : clientes) {
            this.comboClientes.addItem(clienteCombo.getInfoVenta());
        }
    }

    private void llenarTable(List<Producto> productos) {
        dfm = (DefaultTableModel) tableCarrito.getModel();
        dfm.setRowCount(0);
        productos.stream().map(producto -> new String[]{
            producto.getNombre(),
            producto.getPrecio() + "",
            producto.getCantidad() + "",
            producto.getPrecio() * Integer.parseInt(this.txtCantidad.getText()) + "",
            "Quitar"
        }).forEachOrdered(datos -> {
            dfm.addRow(datos);
        });

    }

    private Producto productoEnCarrito(Producto p, List<Producto> productos) {
        for (Producto producto : productos) {
            if (p.getCodigo().equals(producto.getCodigo())) {
                return producto;
            }
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.JButton btnOutoff;
    private javax.swing.JButton btnRegresarTienda;
    private javax.swing.JComboBox<String> comboClientes;
    private javax.swing.JComboBox<String> comboProduts;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableCarrito;
    private javax.swing.JTextField txtBusquedaNit;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
