/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.frontend;

import com.backend.entidad.Cliente;
import com.backend.entidad.Empleado;
import com.backend.entidad.Pedido;
import com.backend.entidad.Producto;
import com.backend.entidad.Sistema;
import com.backend.entidad.TiempoDeEnvio;
import com.backend.entidad.Tienda;
import com.backend.entidad.datos.FileCarga;
import com.tienda.utiles.Utiles;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luis
 */
public class CargaDatos extends javax.swing.JFrame {

    private FileCarga fileCarga;
    private Login login;
    private Sistema sistema;

    private DefaultTableModel model;
    private DefaultTableModel mode1;
    private DefaultTableModel mode2;
    private DefaultTableModel mode3;
    private DefaultTableModel mode4;
    private DefaultTableModel mode5;
    private DefaultTableModel mode6;

    /**
     * Creates new form CargaDatos
     *
     * @param sistema
     * @param login
     */
    public CargaDatos(Sistema sistema, Login login) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Carga masiva de datos");
        Utiles.ponerIconoLabel(labelElegirArchivo, "iconos/file.jpg", 17);
        this.fileCarga = new FileCarga(sistema, login);
        this.sistema = sistema;
        this.login = login;
        llenarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnSubir = new javax.swing.JButton();
        labelElegirArchivo = new javax.swing.JLabel();
        tableHojas = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTienda = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelEnvio = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableProducts = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableCustomers = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableEmployees = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablePedidos = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableErrores = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSubir.setText("Subir datos");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        labelElegirArchivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelElegirArchivo.setText("Elegir archivo");
        labelElegirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelElegirArchivoMouseClicked(evt);
            }
        });

        tableTienda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Código", "Dirección", "Teléfono 1", "Teléfono 1"
            }
        ));
        jScrollPane1.setViewportView(tableTienda);

        tableHojas.addTab("Tiendas", jScrollPane1);

        tabelEnvio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tienda 1", "Tienda 2", "Tiempo"
            }
        ));
        jScrollPane2.setViewportView(tabelEnvio);

        tableHojas.addTab("Tiempo de envío", jScrollPane2);

        tableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Fabricante", "Código", "Cantidad", "Precio unitario", "Tienda"
            }
        ));
        jScrollPane3.setViewportView(tableProducts);

        tableHojas.addTab("Productos", jScrollPane3);

        tableCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "NIT", "Teléfono", "Crédito"
            }
        ));
        jScrollPane6.setViewportView(tableCustomers);

        tableHojas.addTab("Clientes", jScrollPane6);

        tableEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Código", "Teléfono", "DPI"
            }
        ));
        jScrollPane7.setViewportView(tableEmployees);

        tableHojas.addTab("Empleados", jScrollPane7);

        tablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Tienda origen", "Tienda destino", "Fecha", "Cliente", "Artículo", "Cantidad", "Total", "Anticipo"
            }
        ));
        jScrollPane5.setViewportView(tablePedidos);

        tableHojas.addTab("Pedidos", jScrollPane5);

        tableErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contenido de errores de entrada"
            }
        ));
        jScrollPane8.setViewportView(tableErrores);

        tableHojas.addTab("Errores", jScrollPane8);

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableHojas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1461, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelElegirArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubir, javax.swing.GroupLayout.DEFAULT_SIZE, 1175, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelElegirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubir))
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(tableHojas, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelElegirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelElegirArchivoMouseClicked
        // TODO add your handling code here:
        this.fileCarga.cargarDatos();
        llenarTablas();
    }//GEN-LAST:event_labelElegirArchivoMouseClicked

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSubirActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        this.login.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void llenarTablas() {
        model = (DefaultTableModel) tableTienda.getModel();

        for (Tienda tienda : sistema.getTiendas()) {
            String[] datos = new String[]{
                tienda.getNombreTienda(),
                tienda.getCodigo(),
                tienda.getDireccion(),
                tienda.getTelefono(),
                tienda.getTelefono2()
            };
            model.addRow(datos);
        }

        mode1 = (DefaultTableModel) tabelEnvio.getModel();

        for (TiempoDeEnvio envio : sistema.getTiemposDeEnvio()) {
            String[] datos = new String[]{
                envio.getCodigoTIENDA1(),
                envio.getCodigoTIENDA2(),
                envio.getTiempoEnvio() + ""
            };
            mode1.addRow(datos);
        }
        mode2 = (DefaultTableModel) tableCustomers.getModel();
        for (Cliente c : sistema.getClientes()) {
            String[] datos = new String[]{
                c.getNombreCliente(),
                c.getNit(),
                c.getTelefono() + "",
                c.getCredito() + ""
            };
            mode2.addRow(datos);
        }
        mode3 = (DefaultTableModel) tableEmployees.getModel();
        for (Empleado e : sistema.getEmpleados()) {
            String[] datos = new String[]{
                e.getNomgre(),
                e.getCodigo(),
                e.getTelefono() + "",
                e.getDpi() + ""
            };
            mode3.addRow(datos);
        }
        mode4 = (DefaultTableModel) tableErrores.getModel();
        for (String e : sistema.getDatosErroneos()) {
            String[] datos = new String[]{
                e
            };
            mode4.addRow(datos);
        }
        mode5 = (DefaultTableModel) tablePedidos.getModel();
        for (Pedido e : sistema.getPedidos()) {
            String[] datos = new String[]{
                e.getCodigoProductoPedido(),
                e.getCodigoTiendaORIGEN(),
                e.getCodigoTiendaDESTINO(),
                e.getFechaPedido().mostrarFECHAS(),
                e.getNitCliente(),
                e.getCodigoProductoPedido() + "",
                e.getCantidadArticulos() + "",
                e.getTotalPagar() + "",
                e.getAnticipo() + ""

            };
            mode5.addRow(datos);
        }
        mode6 = (DefaultTableModel) tableProducts.getModel();
        for (Producto e : sistema.getProductos()) {
            String[] datos = new String[]{
                e.getNombre(),
                e.getFabricante(),
                e.getCodigo(),
                e.getCantidad() + "",
                e.getPrecio() + "",
                e.getTiendaDondeExiste() + ""
            };
            mode6.addRow(datos);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSubir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel labelElegirArchivo;
    private javax.swing.JTable tabelEnvio;
    private javax.swing.JTable tableCustomers;
    private javax.swing.JTable tableEmployees;
    private javax.swing.JTable tableErrores;
    private javax.swing.JTabbedPane tableHojas;
    private javax.swing.JTable tablePedidos;
    private javax.swing.JTable tableProducts;
    private javax.swing.JTable tableTienda;
    // End of variables declaration//GEN-END:variables
}
