/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.frontend;

import com.backend.entidad.Cliente;
import com.backend.entidad.Empleado;
import com.backend.entidad.Sistema;
import com.frontend.cliente.CatalogoProductos;
import com.mysql.cj.xdevapi.Client;
import javax.swing.JOptionPane;

/**
 *
 * @author luis
 */
public class InicioSesion extends javax.swing.JFrame {

    Sistema sistema;
    Login login;
    Object entidad;

    /**
     * Creates new form InicioSesion
     *
     * @param entidad
     * @param sistema
     * @param login
     */
    public InicioSesion(Object entidad, Sistema sistema, Login login) {
        initComponents();
        setLocationRelativeTo(null);
        this.sistema = sistema;
        this.login = login;
        this.entidad = entidad;
        validarEntidad(entidad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelIngresar = new javax.swing.JLabel();
        btnIgresar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnIgresar.setBackground(new java.awt.Color(51, 255, 0));
        btnIgresar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnIgresar.setText("Ingresar");
        btnIgresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIgresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgresarActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnCancelar.setBackground(new java.awt.Color(255, 102, 51));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(btnIgresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIgresar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIgresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgresarActionPerformed
        // TODO add your handling code here:
        if (txtPassword.getText().isBlank() || txtPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe llenar el campo.", "Campos Vacíos", JOptionPane.INFORMATION_MESSAGE);
        } else {
            validarSesion(this.entidad);
        }
    }//GEN-LAST:event_btnIgresarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void validarEntidad(Object entidad) {
        if (entidad instanceof Empleado) {
            this.labelIngresar.setText("Ingrese su codigo:");
        } else if (entidad instanceof Cliente) {
            this.labelIngresar.setText("Ingrese su NIT:");
        }
    }

    private void validarSesion(Object entidad) {
        if (entidad instanceof Empleado) {
            Empleado empleado = this.sistema.getEmpleadoDB().buscarEmpleado(txtPassword.getText());
            if (empleado == null) {
                JOptionPane.showMessageDialog(this, "Codigo incorrecto", "Codigo de empleado", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (sistema.getTiendaDB().getTiendas().isEmpty()) {
                    setVisible(false);
                    CargaDatos c = new CargaDatos(sistema, login);
                    c.setVisible(true);
                } else {
                    setVisible(false);
                    new VentanaEmpleado(login, sistema).setVisible(true);
                }
            }
        } else if (entidad instanceof Cliente) {
            Cliente cliente = null;
            if (cliente == null) {
                JOptionPane.showMessageDialog(this, "NIT incorrecto", "NIT de cliente", JOptionPane.INFORMATION_MESSAGE);
            } else {
                CatalogoProductos catalogoProductos = new CatalogoProductos(login, sistema, cliente);
                catalogoProductos.setVisible(true);
                setVisible(false);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIgresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelIngresar;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
