/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.frontend;

import com.backend.conectionDB.ConeccionDB;
import com.backend.conectionDB.modelo.TiendaDB;
import com.backend.entidad.Cliente;
import com.backend.entidad.Empleado;
import com.backend.entidad.Sistema;
import com.frontend.cliente.CatalogoProductos;
import com.frontend.cliente.Menu;
import com.tienda.utiles.Utiles;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author luis
 */
public class InicioSesion extends javax.swing.JFrame {

    Sistema sistema;
    Login login;
    Object entidad;

    /**
     * Creates new form InicioSesion
     *
     * @param entidad
     * @param sistema
     * @param login
     */
    public InicioSesion(Object entidad, Sistema sistema, Login login) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconos/tiendaIcono.png")));
        setLocationRelativeTo(null);
        this.sistema = sistema;
        this.login = login;
        this.entidad = entidad;
        validarEntidad(entidad);
        Utiles u = new Utiles();
        u.ponerIconoLabel(jLabel2, "/iconos/door-key.png");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelIngresar = new javax.swing.JLabel();
        btnIgresar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIngresar.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        labelIngresar.setForeground(new java.awt.Color(0, 0, 0));
        labelIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 430, 29));

        btnIgresar.setBackground(new java.awt.Color(0, 204, 153));
        btnIgresar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnIgresar.setForeground(new java.awt.Color(0, 0, 0));
        btnIgresar.setText("Ingresar");
        btnIgresar.setBorder(null);
        btnIgresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIgresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIgresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 168, 223, -1));

        txtPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 118, 223, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 102, 51));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 216, 223, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 0, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIgresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgresarActionPerformed
        // TODO add your handling code here:
        if (txtPassword.getText().isBlank() || txtPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe llenar el campo.", "Campos Vacíos", JOptionPane.INFORMATION_MESSAGE);
        } else {
            validarSesion(this.entidad);
        }
    }//GEN-LAST:event_btnIgresarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            validarSesion(entidad);
        }
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jPanel2.setBackground(Color.red);
        jLabel1.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jPanel2.setBackground(Color.WHITE);
        jLabel1.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void validarEntidad(Object entidad) {
        if (entidad instanceof Empleado) {
            this.labelIngresar.setText("Ingrese su codigo:");
        } else if (entidad instanceof Cliente) {
            this.labelIngresar.setText("Ingrese su NIT:");
        }
    }

    private void validarSesion(Object entidad) {
        if (entidad instanceof Empleado) {
            Empleado empleado = this.sistema.getEmpleadoDB().buscarEmpleado(String.valueOf(txtPassword.getPassword()));
            if (empleado == null) {
                if (!txtPassword.getText().isBlank()) {
                    this.txtPassword.requestFocus();
                    this.txtPassword.setText("");
                    JOptionPane.showMessageDialog(this, "Codigo incorrecto", "Codigo de empleado", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                if (sistema.getTiendaDB().getTiendas(TiendaDB.SELECT_TIENDAS).isEmpty()) {
                    setVisible(false);
                    CargaDatos c = new CargaDatos(sistema, login);
                    c.setVisible(true);
                } else {
                    setVisible(false);
                    new VentanaEmpleado(login, sistema, empleado).setVisible(true);
                }
            }
        } else if (entidad instanceof Cliente) {
            try {
                Cliente cliente = this.sistema.getClienteDB().getClienteByNit(ConeccionDB.getConnection(), String.valueOf(txtPassword.getPassword()));
                if (cliente == null) {
                    if (!txtPassword.getText().isBlank()) {
                        this.txtPassword.requestFocus();
                        this.txtPassword.setText("");
                        JOptionPane.showMessageDialog(this, "NIT incorrecto", "NIT de cliente", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    Menu m = new Menu(login, sistema, cliente);
                    m.setVisible(true);
                    setVisible(false);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIgresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelIngresar;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
