/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frontend;

import com.backend.entidad.Cliente;
import com.backend.entidad.Sistema;
import javax.swing.JOptionPane;

/**
 *
 * @author luis
 */
public class ModificadorCliente extends javax.swing.JFrame {

    private TableClients tableClients;
    private Cliente cliente;
    private Sistema sistema;

    /**
     * Para modificar los datos de un cliente
     *
     * @param tableClients
     * @param cliente
     */
    public ModificadorCliente(TableClients tableClients, Cliente cliente, Sistema sistema) {
        initComponents();
        this.tableClients = tableClients;
        this.cliente = cliente;
        this.sistema = sistema;

        this.txtCorreoElectronico.setText(cliente.getCorreoElctronico());
        this.txtCreditoCliente.setText(cliente.getCredito() + "");
        this.txtDPI_Cliente.setText(cliente.getDPI());
        this.txtDireccionCliente.setText(cliente.getDireccion());
        this.txtNITcliente.setText(cliente.getNit());
        this.txtNombreCliente.setText(cliente.getNombreCliente());
        this.txtTelefono_cliente.setText(cliente.getTelefono());

        super.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtNITcliente = new javax.swing.JTextField();
        txtTelefono_cliente = new javax.swing.JTextField();
        txtDPI_Cliente = new javax.swing.JTextField();
        txtCreditoCliente = new javax.swing.JTextField();
        txtCorreoElectronico = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        btnGuardarDatosCliente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Modificar cliente");

        jLabel2.setText("Nombre: *");

        jLabel3.setText("NIT: *");

        jLabel4.setText("Teléfono: *");

        jLabel5.setText("DPI:");

        jLabel6.setText("Correo Electónico:");

        jLabel7.setText("Credito:");

        jLabel8.setText("Dirección:");

        txtNITcliente.setEditable(false);

        btnGuardarDatosCliente.setText("Guardar datos");
        btnGuardarDatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDatosClienteActionPerformed(evt);
            }
        });

        jLabel9.setText("*campos obligatorios");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardarDatosCliente)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(txtCreditoCliente)
                            .addComponent(txtDPI_Cliente)
                            .addComponent(txtTelefono_cliente)
                            .addComponent(txtNITcliente)
                            .addComponent(txtNombreCliente)
                            .addComponent(txtDireccionCliente, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNITcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefono_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDPI_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCreditoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarDatosCliente)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarDatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDatosClienteActionPerformed
        // TODO add your handling code here:
        if (txtNombreCliente.getText().isEmpty() || (txtTelefono_cliente.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Llene los campos obligatoriso", "CAMPOS OBLIGATORIOS *", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (txtDPI_Cliente.getText().isEmpty()) {
                txtDPI_Cliente.setText("");
                if (txtCreditoCliente.getText().isEmpty()) {
                    txtCreditoCliente.setText("");
                    if (txtDireccionCliente.getText().isEmpty()) {
                        txtDireccionCliente.setText("");
                        if (txtDPI_Cliente.getText().isEmpty()) {
                            txtDPI_Cliente.setText("");
                            if (txtCorreoElectronico.getText().isEmpty()) {
                                txtCorreoElectronico.setText("");
                            }
                        }
                    }
                }
            }
            //se modifica los datos del cliente
            this.cliente.setCorreoElctronico(txtCorreoElectronico.getText());
            this.cliente.setCredito(Double.parseDouble(txtCreditoCliente.getText()));
            this.cliente.setDPI(txtDPI_Cliente.getText());
            this.cliente.setDireccion(txtDireccionCliente.getText());
            this.cliente.setNombreCliente(txtNombreCliente.getText());
            this.cliente.setTelefono(txtTelefono_cliente.getText());
            //se actualiza el cliente en la base de datos
            this.sistema.getConection().modificarCliente(sistema.getConection().getConnection(),
                    cliente.getNombreCliente(),
                    cliente.getTelefono(),
                    cliente.getDPI(),
                    cliente.getCredito() + "",
                    cliente.getCorreoElctronico(),
                    cliente.getDireccion(),
                    cliente.getNit());
        }
        this.txtCorreoElectronico.setText("");
        this.txtCreditoCliente.setText("");
        this.txtDPI_Cliente.setText("");
        this.txtDireccionCliente.setText("");
        this.txtNombreCliente.setText("");
        this.txtTelefono_cliente.setText("");
    }//GEN-LAST:event_btnGuardarDatosClienteActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.tableClients.setVisible(true);
        super.setVisible(false);
        this.tableClients.llenarTableClients();
    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarDatosCliente;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtCreditoCliente;
    private javax.swing.JTextField txtDPI_Cliente;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtNITcliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefono_cliente;
    // End of variables declaration//GEN-END:variables
}
