/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frontend;

import com.backend.entidad.Producto;
import com.backend.entidad.Sistema;
import com.backend.entidad.Tienda;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luis
 */
public class VentanaTienda extends javax.swing.JFrame {

    private VentanaEmpleado ventanaEmpleado;
    private Sistema sistema;
    private String tiendaSeleccionada;
    private Producto productoBuscado;
    
    private RegistroNuevoProducto registroNuevoProducto;
    private RegistroNuevaTienda registroNuevaTienda;
    private TableStores tableStores;
    private VerificadorTiempoEnvio verifidorTiempoEnvio;
    private Tienda tiendaActual;

    private DefaultTableModel dfm;

    /**
     * Creates new form VentanaTienda
     * @param ventanaEmpleado
     * @param sistema
     * @param tiendaSeleccionada
     */
    public VentanaTienda(VentanaEmpleado ventanaEmpleado, Sistema sistema, String tiendaSeleccionada) {
        initComponents();
        this.ventanaEmpleado = ventanaEmpleado;
        this.sistema = sistema;
        this.tiendaSeleccionada = tiendaSeleccionada;
        this.tiendaActual = this.sistema.buscarTienda(tiendaSeleccionada);

        llenarTablaProductos();

        super.setTitle("                 TIENDA: " + tiendaActual.getNombreTienda());
        super.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTienda = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        spinerCantidaProductos = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProducts = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarExistencias = new javax.swing.JButton();
        btnOrdenarProductoPorCodigo = new javax.swing.JButton();
        btnRegistrarProducto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRegitroTienda = new javax.swing.JButton();
        btnTablaTiendas = new javax.swing.JButton();
        btnVERtiempoEnvio = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        txtFechaSistema = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        spinerCantidaProductos.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        tableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "FABRICANTE", "CODIGO", "CANTIDAD", "PRECIO", "DESCRIPCIÓN", "GARANTÍA"
            }
        ));
        jScrollPane1.setViewportView(tableProducts);

        jLabel1.setText("Seleccione el producto");

        btnAgregarExistencias.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAgregarExistencias.setText("Agregar nuevas existencias");
        btnAgregarExistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarExistenciasActionPerformed(evt);
            }
        });

        btnOrdenarProductoPorCodigo.setText("ORDENAR POR CÓDIGO");
        btnOrdenarProductoPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarProductoPorCodigoActionPerformed(evt);
            }
        });

        btnRegistrarProducto.setText("REGISTRAR PRODUCTO");
        btnRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProductoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("PRODUCTOS");

        btnRegitroTienda.setText("Registra nueva tienda");
        btnRegitroTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegitroTiendaActionPerformed(evt);
            }
        });

        btnTablaTiendas.setText("Ver tiendas");
        btnTablaTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaTiendasActionPerformed(evt);
            }
        });

        btnVERtiempoEnvio.setText("Ver tiempo de envío a otras tiendas");
        btnVERtiempoEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVERtiempoEnvioActionPerformed(evt);
            }
        });

        btnVentas.setText("Ventas");

        javax.swing.GroupLayout panelTiendaLayout = new javax.swing.GroupLayout(panelTienda);
        panelTienda.setLayout(panelTiendaLayout);
        panelTiendaLayout.setHorizontalGroup(
            panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTiendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTiendaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(panelTiendaLayout.createSequentialGroup()
                        .addGroup(panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOrdenarProductoPorCodigo)
                            .addComponent(btnRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTiendaLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel1))
                            .addGroup(panelTiendaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarExistencias))
                            .addGroup(panelTiendaLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(spinerCantidaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTiendaLayout.createSequentialGroup()
                                .addGroup(panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRegitroTienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVERtiempoEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTablaTiendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                                .addComponent(btnSalir)
                                .addGap(98, 98, 98))
                            .addGroup(panelTiendaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(546, 546, 546))))))
        );
        panelTiendaLayout.setVerticalGroup(
            panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTiendaLayout.createSequentialGroup()
                .addGroup(panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTiendaLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegitroTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTablaTiendas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(btnVERtiempoEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelTiendaLayout.createSequentialGroup()
                        .addGroup(panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTiendaLayout.createSequentialGroup()
                                .addContainerGap(22, Short.MAX_VALUE)
                                .addComponent(txtFechaSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgregarExistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelTiendaLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOrdenarProductoPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinerCantidaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        super.setVisible(false);
        this.ventanaEmpleado.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarExistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarExistenciasActionPerformed
        // TODO add your handling code here:
        int fila = this.tableProducts.getSelectedRow();
        System.out.println(fila);

        if (fila > -1) {
            //try {
            String codigo = String.valueOf(this.dfm.getValueAt(fila, 2));
            this.productoBuscado = this.sistema.buscarProducto(codigo);
            System.out.println(productoBuscado.getCantidad());

            int cantidad = (int) this.spinerCantidaProductos.getValue();
            System.out.println(cantidad);

            int cantidadNueva = productoBuscado.getCantidad() + cantidad;
            this.productoBuscado.setCantidad(cantidadNueva);
            System.out.println(productoBuscado.getCantidad());
            dfm.setRowCount(0);
            llenarTablaProductos();
            //} catch (Exception e) {
            //}
        }
    }//GEN-LAST:event_btnAgregarExistenciasActionPerformed

    private void btnRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProductoActionPerformed
        // TODO add your handling code here:
        this.registroNuevoProducto = new RegistroNuevoProducto(this, sistema, this.tiendaSeleccionada);
        this.registroNuevoProducto.setVisible(true);
        dfm.setRowCount(0);
        super.setVisible(false);
    }//GEN-LAST:event_btnRegistrarProductoActionPerformed

    private void btnOrdenarProductoPorCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarProductoPorCodigoActionPerformed
        // TODO add your handling code here:
        dfm.setRowCount(0);
        this.sistema.ordenarProductosPorCodigo();
        llenarTablaProductos();
    }//GEN-LAST:event_btnOrdenarProductoPorCodigoActionPerformed

    private void btnRegitroTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegitroTiendaActionPerformed
        // TODO add your handling code here:
        this.registroNuevaTienda = new RegistroNuevaTienda(this, ventanaEmpleado, verifidorTiempoEnvio, sistema);
        this.registroNuevaTienda.setVisible(true);
        //this.verifidorTiempoEnvio.getDfm().setRowCount(0);
        super.setVisible(false);
    }//GEN-LAST:event_btnRegitroTiendaActionPerformed

    private void btnTablaTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaTiendasActionPerformed
        // TODO add your handling code here:
        this.tableStores = new TableStores(this, sistema);
        this.tableStores.setVisible(true);
    }//GEN-LAST:event_btnTablaTiendasActionPerformed

    private void btnVERtiempoEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVERtiempoEnvioActionPerformed
        // TODO add your handling code here:
        this.verifidorTiempoEnvio = new VerificadorTiempoEnvio(this, this.sistema, this.tiendaActual);
        this.verifidorTiempoEnvio.setVisible(true);
        //this.verifidorTiempoEnvio.getDfm().setRowCount(0);
    }//GEN-LAST:event_btnVERtiempoEnvioActionPerformed

    public void llenarTablaProductos() {
        dfm = (DefaultTableModel) tableProducts.getModel();

        for (Producto producto : this.sistema.getProductos()) {
            if (producto.getTiendaDondeExiste().equals(this.tiendaSeleccionada)) {
                String[] datos = {producto.getNombre(),
                    producto.getFabricante(),
                    producto.getCodigo(),
                    producto.getCantidad() + "",
                    producto.getPrecio() + "",
                    producto.getDescripcion(),
                    producto.getGarantia()
                };
                dfm.addRow(datos);
            }

        }
    }

    public VerificadorTiempoEnvio getVerifidorTiempoEnvio() {
        return verifidorTiempoEnvio;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarExistencias;
    private javax.swing.JButton btnOrdenarProductoPorCodigo;
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JButton btnRegitroTienda;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTablaTiendas;
    private javax.swing.JButton btnVERtiempoEnvio;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelTienda;
    private javax.swing.JSpinner spinerCantidaProductos;
    private javax.swing.JTable tableProducts;
    private javax.swing.JLabel txtFechaSistema;
    // End of variables declaration//GEN-END:variables
}
